### ISSUE TITLE
Seeder nie działa po zmianie migracji 

### ISSUE THREAD

**Issue by torczyk** [monikadulik/SyMag#1]
Aby naprawić problem z niedziałającym seederem po zmianie nazwy tabeli w migracji należy wykonać następujące polecenia:

composer dump-autoload

php artisan cache:clear

php artisan optimize

php artisan db:seed  [lub] php artisan db:seed --class=NazwaTabeliSeeder

**Comment by monikadulik** [comment]
Niestety, powyższe polecenia nie wystarczyły - dalej występował ten sam błąd.

Problem udało się rozwiązać przez dodanie linii `protected $table = 'order_items';` do pliku modelu tabeli (ustawienie nowej nazwy). Jednak aby uniknąć w przyszłości problemów ostatecznie wygenerowałam model z **nową** nazwą "OrderItems.php". Laravel automatycznie szukał migracji ze znakiem podkreślenia pomiędzy kolejnymi słowami w nazwie modelu. Prawdopodobnie to poprzednia nazwa "Order_Items.php" skutkowała ciągłym szukaniem pliku migracji z podwójnym znakiem podkreślenia.
